#!/bin/bash

apt-get update && apt-get upgrade

apt-get install sudo && adduser vimucchi sudo

login vimucchi

sudo apt-get install zsh
sudo apt-get install curl
sudo apt-get install git
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

sudo apt-get upgrade vim
cd
echo "set number\nsyntax on\n set mouse=a" > .vimrc
